version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    environment:
      PYTHONPATH: /home/circleci/project/
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
            pip install pytest-mock
            # pip install -r requirements.txt
      - run:
          name: run test
          command: |
            . ../venv/bin/activate
            pytest -v -l --durations=0 --cov=. --cov-report=term-missing --showlocals
          working_directory: ./tests
      - store-test-results:
          path: ./tests
